/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author naufa
 */
public class mainView extends javax.swing.JFrame {
    
    DefaultListModel modelList;
    
    /**
     * Creates new form designView
     */
    public mainView() {
        initComponents();
        modelList = new DefaultListModel();
    }
    
    private void addElementList(double IMT, double tb, double bb, String kategori) {
        modelList.addElement(String.format("(%.1f / %s) %.2fcm %.2fkg", IMT, kategori, tb*100, bb));
        list_riwayatInput.setModel(modelList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_tinggiBadan = new javax.swing.JTextField();
        input_beratBadan = new javax.swing.JTextField();
        btn_hitungIMT = new javax.swing.JButton();
        btn_syaratInput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_riwayatInput = new javax.swing.JList<>();
        btn_tableIMT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menghitung IMT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        input_tinggiBadan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        input_tinggiBadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tinggiBadanActionPerformed(evt);
            }
        });

        input_beratBadan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_hitungIMT.setBackground(new java.awt.Color(0, 102, 235));
        btn_hitungIMT.setForeground(new java.awt.Color(255, 255, 255));
        btn_hitungIMT.setText("Hitung IMT");
        btn_hitungIMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hitungIMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungIMTActionPerformed(evt);
            }
        });

        btn_syaratInput.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_syaratInput.setForeground(new java.awt.Color(255, 0, 51));
        btn_syaratInput.setText("Lihat syarat pengisian");
        btn_syaratInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_syaratInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_syaratInputMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(list_riwayatInput);

        btn_tableIMT.setBackground(new java.awt.Color(235, 235, 235));
        btn_tableIMT.setText("Tabel IMT");
        btn_tableIMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tableIMT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tableIMTMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menghitung Index Massa Tubuh");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Tinggi Badan (cm)");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Berat Badan (kg)");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Terjadi Kesalahan Saat Mengisi?");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Riwayat Pengisian :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_syaratInput)))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_tinggiBadan)
                            .addComponent(input_beratBadan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_tableIMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hitungIMT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_tinggiBadan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_beratBadan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_hitungIMT, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btn_tableIMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_syaratInput)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popUp(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    private void input_tinggiBadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tinggiBadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tinggiBadanActionPerformed

    private void btn_syaratInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_syaratInputMouseClicked
        syaratPengisianView sPW = new syaratPengisianView();
        sPW.setVisible(true);
        sPW.setDefaultCloseOperation(WIDTH);
    }//GEN-LAST:event_btn_syaratInputMouseClicked

    private void btn_tableIMTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tableIMTMouseClicked
        tableIMTView tIMT = new tableIMTView();
        tIMT.setVisible(true);
        tIMT.setDefaultCloseOperation(WIDTH);
    }//GEN-LAST:event_btn_tableIMTMouseClicked

    private void tingkatBerat(double IMT, double tb, double bb, String kategori) {
        redView tingkatBerat = new redView();
        tingkatBerat.red_IMT.setText(String.format("IMT: %.1f", IMT));
        tingkatBerat.red_kategori.setText(kategori);
        tingkatBerat.red_tb.setText(String.format("%.2f cm", tb*100));
        tingkatBerat.red_bb.setText(String.format("%.2f kg", bb));
        tingkatBerat.setVisible(true);
        tingkatBerat.setDefaultCloseOperation(WIDTH);
    }
    
    private void tingkatRingan(double IMT, double tb, double bb, String kategori) {
        yellowView tingkatRingan = new yellowView();
        tingkatRingan.yellow_IMT.setText(String.format("IMT: %.1f", IMT));
        tingkatRingan.yellow_kategori.setText(kategori);
        tingkatRingan.yellow_tb.setText(String.format("%.2f cm", tb*100));
        tingkatRingan.yellow_bb.setText(String.format("%.2f kg", bb));
        tingkatRingan.setVisible(true);
        tingkatRingan.setDefaultCloseOperation(WIDTH);
    }
    
    private void tingkatNormal(double IMT, double tb, double bb, String kategori) {
        greenView tingkatNormal = new greenView();
        tingkatNormal.green_IMT.setText(String.format("IMT: %.1f", IMT));
        tingkatNormal.green_kategori.setText(kategori);
        tingkatNormal.green_tb.setText(String.format("%.2f cm", tb*100));
        tingkatNormal.green_bb.setText(String.format("%.2f kg", bb));
        tingkatNormal.setVisible(true);
        tingkatNormal.setDefaultCloseOperation(WIDTH);
    } 
    
    private void btn_hitungIMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungIMTActionPerformed
        double tb = 0.0,
               bb = 0.0,
               IMT = 0.0;
        String kategori = "";
        boolean lanjut = true;
        syaratPengisianView sPW = new syaratPengisianView();
        
        try {
            tb = Double.parseDouble(input_tinggiBadan.getText());
            bb = Double.parseDouble(input_beratBadan.getText());
        } catch (Exception e) {
            lanjut = false;
            sPW.setVisible(true);
        }
        
        if (lanjut) {
            
            // RUMUS IMT
            tb = tb / 100;
            IMT = bb / (tb * tb);
            
            if (IMT < 17) {
                kategori = "Kurus Tingkat Berat";
                tingkatBerat(IMT, tb, bb, kategori);
            } else if (IMT < 18.5) {
                kategori = "Kurus Tingkat Ringan";
                tingkatRingan(IMT, tb, bb, kategori);
            } else if (IMT < 25.1) {
                kategori = "Normal";
                tingkatNormal(IMT, tb, bb, kategori);
            } else if (IMT < 27.1) {
                kategori = "Gemuk Tingkat Ringan";
                tingkatRingan(IMT, tb, bb, kategori);
            } else {
                kategori = "Gemuk Tingkat Berat";
                tingkatBerat(IMT, tb, bb, kategori);
            }
            
            addElementList(IMT, tb, bb, kategori);
        }
        
    }//GEN-LAST:event_btn_hitungIMTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitungIMT;
    private javax.swing.JLabel btn_syaratInput;
    private javax.swing.JButton btn_tableIMT;
    private javax.swing.JTextField input_beratBadan;
    private javax.swing.JTextField input_tinggiBadan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_riwayatInput;
    // End of variables declaration//GEN-END:variables
}
